// GENERATED FILE (placeholder)
//
// This file is usually generated by running `flutterfire configure`.
// Replace this placeholder by running `flutterfire configure --project=YOUR_PROJECT_ID`
// which will produce a concrete `DefaultFirebaseOptions` implementation.

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnimplementedError(
      'DefaultFirebaseOptions is not configured. Run `flutterfire configure` to generate this file.',
    );
  }
}
